export const YEAR = '2021'
export const TITLE = 'Simple Blog'
export const DESCRIPTION = 'No images, just text.'
export const AUTHOR = 'Nina Armangué Braun'
export const URL = 'https://github.com/clairstudiobcn/simple-blog'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL = 'https://github.com/clairstudiobcn/simple-blog/public/images/banner.jpg'
